### ISSUE TITLE
ConnectionToClient.getHostName() does not exist

### ISSUE THREAD

**Issue by rgavs** [rgavs/SimpleChat#15]
New issue introduced in commit f0e06b2, author @JingxianWu. References to .getHostName() must either be replaced with new identifier or the method must be created in ConnectionToClient

Affected files:
src/SimpleChatServer/privateMessage.java
src/SimpleChatServer/ServerMessageHandler.java
indirect:
    src/ocsf/server/ConnectionToClient.java

**Comment by shouhengwu** [comment]
Solved by changing client.getHostName() to client.getInetAddress().getHostName()
